- name: "nxos.lldp_neighbors: show lldp neighbors"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show lldp neighbors"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: "{{ fact_key }}"
