- name: "eos.system: show version"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show version"
        set_fact: True
        transform:
        - name: camel_to_snake
        - name: set_root_key
          key: version
        - name: set_root_key
          key: system
        - name: set_root_key
          key: "{{ fact_key }}"
