- name: "nxos.cdp_neighbors: show cdp neighbors"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show cdp neighbors"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: cdp_neighbors
        - name: set_root_key
          key: "{{ fact_key }}"
