- name: "nxos.interfaces: show interface"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show interface"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
          plural: true
        - name: set_root_key
          key: "{{ fact_key }}"
